version: "2.11"
services:
  scrapyd:
#    image: napoler/scrapyd:latest
    image: napoler/scrapyd:2.11
    container_name: scrapyd
    #network_mode: host
    volumes:
      - /data/scrapyd:/app
    ports:
      - 6800:6800
    restart: unless-stopped
  gerapy:
    image: germey/gerapy:latest
    container_name: gerapy
    #network_mode: host
    volumes:
      - /data/gerapy:/app/gerapy
#      - /data:/data
    ports:
      - 8001:8000
    restart: unless-stopped