version: "2.1"
services:
  scrapyd1:
#    image: napoler/scrapyd:latest
    image: napoler/scrapyd:2.11
#    build:
#      context: ./
    container_name: scrapyd1
    #network_mode: host
#    volumes:
      #- /path/app:/app
    ports:
      - 6801:6800
    restart: unless-stopped
#
#  gerapy:
#    image: germey/gerapy:latest
#    container_name: gerapy
#    #network_mode: host
#    volumes:
#      - /data/gerapy:/app/gerapy
#      - /data:/data
#    ports:
#      - 8001:8000
#    restart: unless-stopped
