name: build
on:
  push:
    branches:
    - 1.60
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v1
    - name: Docker Login
      run: docker login -u napoler -p ${{ secrets.DOCKERHUB_LOGIN_PASSWORD }}
    - name: Build the Docker Image
      run: |
        docker build -t napoler/scrapyd:1.60 .
    - name: Push the Docker Image
      run: docker push napoler/scrapyd:1.60

    - name: Docker Login github
      # run: docker login -u napoler -p ${{ secrets.GIB_TOKENS }}
      #run:  docker login ghcr.io -u USERNAME -p {{ secrets.GIB_TOKENS }}
      run: echo {{ secrets.GIB_TOKENS }} | docker login ghcr.io -u USERNAME --password-stdin

    - name: rename the Docker Image
      run: docker tag napoler/scrapyd:1.60 ghcr.io/napoler/scrapyd:1.60
    - name: Push the Docker Image to github
      run: docker push ghcr.io/napoler/scrapyd:1.60
